update of fare specs
hove-io/ntfs-specification pull request #12
Opened 2020-01-14 16:30 UTC by pbench

to reflect the changes made to handle fare v2 to fare v1 conversion

- [ ] https://github.com/CanalTP/transit_model/pull/509
- [ ] https://github.com/CanalTP/navitia/pull/3106

2020-02-18 18:26 UTC, pbougue reviewed
:+1:
Iteration over sections of the journey only concerns pure-PT sections, right? If so, it may be worth mentioning it at the beginning.

2020-02-18 18:26 UTC, pbougue commented on ntfs_fare_extension_fr_deprecated.md
> +- coût le moins cher possible
```suggestion
- coûte le moins cher possible
```

2020-02-18 18:26 UTC, pbougue commented on ntfs_fare_extension_fr_deprecated.md
> +- on parcoure l'ensemble des lignes du fichier fares.csv
```suggestion
- on parcourt l'ensemble des lignes du fichier fares.csv 
```

2020-02-18 18:26 UTC, pbougue commented on ntfs_fare_extension_fr_deprecated.md
> +- une ligne de ce fichier est une _transition valide_ si les conditions avant/après changement et début/fin de trajet sont vérifiée
```suggestion
- une ligne de ce fichier est une _transition valide_ si les conditions avant/après changement et début/fin de trajet sont vérifiées
```

2020-02-18 18:26 UTC, pbougue commented on ntfs_fare_extension_fr_deprecated.md
> +- s'il existe un transition valide dont le champ "condition globale" vaut "exclusive", alors les autres transitions valides ne sont pas considérées (i.e. on ne va pas créer de séquence de ticket cand
```suggestion
- s'il existe une transition valide dont le champ "condition globale" vaut "exclusive", alors les autres transitions valides ne sont pas considérées (i.e. on ne va pas créer de séquence de ticket canditate pour ces autres transitions valides)
```

2020-02-18 18:26 UTC, pbougue commented on ntfs_fare_extension_fr_deprecated.md
> +- on obtient ainsi plusieurs séquence de ticket candidate pour l'itinéraire. Le moteur renverra la séquence coutant le moins cher.
```suggestion
- on obtient ainsi plusieurs séquences de tickets candidates pour l'itinéraire. Le moteur renverra la séquence coûtant le moins cher.
```

2020-02-18 18:26 UTC, pbougue commented on ntfs_fare_extension_fr_deprecated.md
> +- s'il existe un transition valide dont le champ "condition globale" vaut "exclusive", alors les autres transitions valides ne sont pas considérées (i.e. on ne va pas créer de séquence de ticket cand
What if there are multiple "exclusive" transitions valid ?

2020-02-18 18:26 UTC, pbougue commented on ntfs_fare_extension_fr_deprecated.md
> +- on sélectionne enfin la séquence de ticket candidate la moins chez parmi celle qui couvrent l'ensemble de l'itinéraire
```suggestion
- on sélectionne enfin la séquence de tickets candidate la moins chère parmi celles qui couvrent l'ensemble de l'itinéraire
```

2020-02-18 18:26 UTC, pbougue commented on ntfs_fare_extension_fr_deprecated.md
> +
minor: useless newlines

2020-02-19 09:41 UTC, pbench commented
@pbougue thanks for the detailed review ! I updated the PR accordingly

2020-02-21 19:38 UTC, pbougue approved these changes

2020-02-21 19:38 UTC, pbougue commented on ntfs_fare_extension_fr_deprecated.md
> +- s'il existe une transition valide dont le champ "condition globale" vaut "exclusive", alors les autres transitions valides ne sont pas considérées (i.e. on ne va pas créer de séquence de ticket can
```suggestion
- s'il existe une transition valide dont le champ "condition globale" vaut "exclusive", alors les autres transitions valides ne sont pas considérées (i.e. on ne va pas créer de séquence de ticket canditate pour ces autres transitions valides). Si plusieurs transitions "exclusive" sont valides, une est selectionnée arbitrairement.
```

2020-02-26 11:21 UTC, prhod requested changes
I've some questions (in french :p ), it may be only wording.

2020-02-26 11:21 UTC, prhod commented on ntfs_fare_extension_fr_deprecated.md
> +- pour chaque transition valide, on crée une séquence de tickets candidate pour être le résultat final.
dans "séquence de tickets candidate" est-ce qu'on parle d'une "liste de tickets candidats" ?
Quand on a une seule section d'itinéraire, je ne pense pas qu'on puisse avaoir plusieurs tickets comme résultat final.

2020-02-26 11:21 UTC, prhod commented on ntfs_fare_extension_fr_deprecated.md
> +- on commence comme précédemment avec la première section de transport en commun, on obtient alors plusieurs séquences de ticket candidates.
pourquoi plusieurs séquences alors qu'on n'en avait qu'une seule dans le cas précédent ?

2020-02-26 12:59 UTC, pbench commented on ntfs_fare_extension_fr_deprecated.md
> +- pour chaque transition valide, on crée une séquence de tickets candidate pour être le résultat final.
Oui, quand on parle de "séquence de tickets candidate" on parle d'une "liste de tickets qui est candidate (la liste) pour être valide pour l'itinéraire en cours d'évaluation". 
Quand l'itinéraire ne comporte qu'une seule section, la "séquence de tickets" ne contiendra effectivement qu'un seul ticket. J'ai gardé "séquence de tickets" pour avoir un vocabulaire cohérent avec le cas expliqué plus bas d'un itinéraire comportant plusieurs sections. 
Je peux préciser dans le texte

2020-02-26 13:36 UTC, prhod approved these changes
thanks for the hard work and the specs :+1:

2020-02-26 14:41 UTC, papailio reviewed
Just some typos, otherwise it's ok!

2020-02-26 14:41 UTC, papailio commented on ntfs_fare_extension.md
> +To be valid, a ticket_use_id must be appears in at least one line of ticket_use_perimeters.txt
To be valid, a ticket_use_id must appear in at least one line of ticket_use_perimeters.txt

2020-02-26 14:41 UTC, papailio commented on ntfs_fare_extension_fr_deprecated.md
> +60 minutes au moment du *débarquement* du le prochain transport en commun
60 minutes au moment du *débarquement* du prochain transport en commun

2020-02-26 14:41 UTC, papailio commented on ntfs_fare_extension_fr_deprecated.md
> +* Restriction à ligne spécifique. préciser dans le champ la valeur _"ligne=[line_id]"_
* Restriction à une ligne spécifique : préciser dans le champ la valeur _"ligne=[line_id]"_

2020-02-26 14:41 UTC, papailio commented on ntfs_fare_extension_fr_deprecated.md
> +* Interdiction d'un ligne spécifique. préciser dans le champ la valeur _"ligne!=[line_id]"_
* Interdiction d'un ligne spécifique : préciser dans le champ la valeur _"ligne!=[line_id]"_

2020-02-26 14:41 UTC, papailio commented on ntfs_fare_extension_fr_deprecated.md
> +* Les conditions décrit ci-dessus peuvent être mis ensemble en séparant les conditions par des _"&"_
* Les conditions décrites ci-dessus peuvent être mises ensemble en séparant les conditions par des _"&"_

2020-02-26 15:50 UTC, pbench commented
> Just some typos, otherwise it's ok!

Thanks for your sharp eyes ! I updated the PR accordingly

2020-02-26 15:51 UTC, merged